### ISSUE TITLE
[TELA HOW TO PLAY] Index Issues

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#17]
## 2. Tela Inicial 2 - How to play
<img width="841" alt="Captura de Tela 2021-06-16 às 16 50 15" src="https://user-images.githubusercontent.com/82957414/122293353-4f5c5200-cecd-11eb-8075-bfef7d855b7a.png">

- [ ] (2.1) Background em alta #18 
  - aguardando envio da imagem pelo designer
 
- [ ] (2.2) Cabeçalho #19 
   - título: "use your keyboard to travel"
   -  subtítulo: "roam"

- [ ] (2.3) Guia dos botões com as legendas #21  (letras diferentes)

- [ ] (2.4) Letreiro inferior "press Q to enter site or W to go back" #22 (as letras podem ser diferentes)
