### ISSUE TITLE
[HUD] Index Issues

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/roam#9]
## 0. HUD

- [x] (0.1) Botões WASD movimentação #10 

- [ ] (0.1) Botões ERQF #11 

- [x] (0.3) Press Q for Key Guide #12 

- [x] (0.4) Objetos principais visitados #13 

- [x] (0.5) Conteúdo extra visitado #14 

- [x] (0.6) Logo Novas Frequências raiozinho #15 
  
- [ ] (0.7) Anel #16
